### ISSUE TITLE
loader.js locked to 3.2.1

### ISSUE THREAD

**Issue by nybblr** [tim-evans/dom-ruler#5]
A more flexible spec would be better here:
https://github.com/tim-evans/dom-ruler/blob/master/bower.json#L4

I'm using Loader.js 3.3.0 so unfortunately bower install fails due to the locked down loader.

**Comment by tim-evans** [comment]
oooo. that's logical

**Comment by nybblr** [comment]
:smile:

**Comment by tim-evans** [comment]
Fixed in 0.1.9 :tada:

**Comment by nybblr** [comment]
For the last bit of fun, this adjustment may need to be made in autoresize as well (I thought it was just in dom-ruler, whoops!)

https://github.com/tim-evans/ember-autoresize/blob/master/bower.json

**Comment by tim-evans** [comment]
Yuppp! I'll get on that as well

**Comment by nybblr** [comment]
:+1: thanks! This makes my CI builds super happy.

**Comment by tim-evans** [comment]
@nybblr published ember-autoresize 0.5.4

**Comment by nybblr** [comment]
Success! bower install ran without any warnings now. :balloon:
