### ISSUE TITLE
dom-ruler.amd.js missing from bower v0.2.1

### ISSUE THREAD

**Issue by urbany** [tim-evans/dom-ruler#7]
Hi, it seems like the dist folder is missing from version 0.2.1 and `dom-ruler.amd.js` can't be found.

This file is what ember-autoresize tries to load: https://github.com/tim-evans/ember-autoresize/blob/master/index.js#L11

**Comment by tim-evans** [comment]
Sorry about that! 0.2.3 should work

**Comment by tim-evans** [comment]
Lemme update ember-autoresize to fix that reference as well

**Comment by urbany** [comment]
Working great now Tim (0.2.4), thank you so much for the quick reply 👍

**Comment by tim-evans** [comment]
No problemo
